/*
 * OS serive REST API
 * Documentação da API do OS service
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * BalancaResponse
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-09-26T16:38:53.309911-04:00[America/Havana]")
public class BalancaResponse {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private Integer id;

  public static final String SERIALIZED_NAME_MARCA = "marca";
  @SerializedName(SERIALIZED_NAME_MARCA)
  private String marca;

  public static final String SERIALIZED_NAME_MODELO = "modelo";
  @SerializedName(SERIALIZED_NAME_MODELO)
  private String modelo;

  public static final String SERIALIZED_NAME_NOME = "nome";
  @SerializedName(SERIALIZED_NAME_NOME)
  private String nome;

  public static final String SERIALIZED_NAME_NUMERO_IMETRO = "numeroImetro";
  @SerializedName(SERIALIZED_NAME_NUMERO_IMETRO)
  private String numeroImetro;

  public static final String SERIALIZED_NAME_PORTARIA = "portaria";
  @SerializedName(SERIALIZED_NAME_PORTARIA)
  private String portaria;


  public BalancaResponse id(Integer id) {
    
    this.id = id;
    return this;
  }

   /**
   * codigo da balacna
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "5", value = "codigo da balacna")

  public Integer getId() {
    return id;
  }


  public void setId(Integer id) {
    this.id = id;
  }


  public BalancaResponse marca(String marca) {
    
    this.marca = marca;
    return this;
  }

   /**
   * marca da balanca
   * @return marca
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "filizola", value = "marca da balanca")

  public String getMarca() {
    return marca;
  }


  public void setMarca(String marca) {
    this.marca = marca;
  }


  public BalancaResponse modelo(String modelo) {
    
    this.modelo = modelo;
    return this;
  }

   /**
   * modelo da balanca
   * @return modelo
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "filizola", value = "modelo da balanca")

  public String getModelo() {
    return modelo;
  }


  public void setModelo(String modelo) {
    this.modelo = modelo;
  }


  public BalancaResponse nome(String nome) {
    
    this.nome = nome;
    return this;
  }

   /**
   * nome da balanca
   * @return nome
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "prix", value = "nome da balanca")

  public String getNome() {
    return nome;
  }


  public void setNome(String nome) {
    this.nome = nome;
  }


  public BalancaResponse numeroImetro(String numeroImetro) {
    
    this.numeroImetro = numeroImetro;
    return this;
  }

   /**
   * Numero do imetro
   * @return numeroImetro
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "13123987", value = "Numero do imetro")

  public String getNumeroImetro() {
    return numeroImetro;
  }


  public void setNumeroImetro(String numeroImetro) {
    this.numeroImetro = numeroImetro;
  }


  public BalancaResponse portaria(String portaria) {
    
    this.portaria = portaria;
    return this;
  }

   /**
   * portaria
   * @return portaria
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "999786-0000", value = "portaria")

  public String getPortaria() {
    return portaria;
  }


  public void setPortaria(String portaria) {
    this.portaria = portaria;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BalancaResponse balancaResponse = (BalancaResponse) o;
    return Objects.equals(this.id, balancaResponse.id) &&
        Objects.equals(this.marca, balancaResponse.marca) &&
        Objects.equals(this.modelo, balancaResponse.modelo) &&
        Objects.equals(this.nome, balancaResponse.nome) &&
        Objects.equals(this.numeroImetro, balancaResponse.numeroImetro) &&
        Objects.equals(this.portaria, balancaResponse.portaria);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, marca, modelo, nome, numeroImetro, portaria);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BalancaResponse {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    marca: ").append(toIndentedString(marca)).append("\n");
    sb.append("    modelo: ").append(toIndentedString(modelo)).append("\n");
    sb.append("    nome: ").append(toIndentedString(nome)).append("\n");
    sb.append("    numeroImetro: ").append(toIndentedString(numeroImetro)).append("\n");
    sb.append("    portaria: ").append(toIndentedString(portaria)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

