/*
 * OS serive REST API
 * Documentação da API do OS service
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * ClientRequest
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-09-26T16:38:53.309911-04:00[America/Havana]")
public class ClientRequest {
  public static final String SERIALIZED_NAME_CPF_PCPJ = "cpfPcpj";
  @SerializedName(SERIALIZED_NAME_CPF_PCPJ)
  private String cpfPcpj;

  public static final String SERIALIZED_NAME_ENDERECO = "endereco";
  @SerializedName(SERIALIZED_NAME_ENDERECO)
  private String endereco;

  public static final String SERIALIZED_NAME_NOME_FANTASIA = "nomeFantasia";
  @SerializedName(SERIALIZED_NAME_NOME_FANTASIA)
  private String nomeFantasia;

  public static final String SERIALIZED_NAME_RAZAO_SOCIAL = "razaoSocial";
  @SerializedName(SERIALIZED_NAME_RAZAO_SOCIAL)
  private String razaoSocial;


  public ClientRequest cpfPcpj(String cpfPcpj) {
    
    this.cpfPcpj = cpfPcpj;
    return this;
  }

   /**
   * CPF ou CNPJ do cliente
   * @return cpfPcpj
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "75264895148", value = "CPF ou CNPJ do cliente")

  public String getCpfPcpj() {
    return cpfPcpj;
  }


  public void setCpfPcpj(String cpfPcpj) {
    this.cpfPcpj = cpfPcpj;
  }


  public ClientRequest endereco(String endereco) {
    
    this.endereco = endereco;
    return this;
  }

   /**
   * Endereco do cliente
   * @return endereco
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "Rua de algum lugar numero 53", value = "Endereco do cliente")

  public String getEndereco() {
    return endereco;
  }


  public void setEndereco(String endereco) {
    this.endereco = endereco;
  }


  public ClientRequest nomeFantasia(String nomeFantasia) {
    
    this.nomeFantasia = nomeFantasia;
    return this;
  }

   /**
   * Nome fantasia
   * @return nomeFantasia
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "Josenildo Cachaças", value = "Nome fantasia")

  public String getNomeFantasia() {
    return nomeFantasia;
  }


  public void setNomeFantasia(String nomeFantasia) {
    this.nomeFantasia = nomeFantasia;
  }


  public ClientRequest razaoSocial(String razaoSocial) {
    
    this.razaoSocial = razaoSocial;
    return this;
  }

   /**
   * Razão social
   * @return razaoSocial
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "Conveniencia", value = "Razão social")

  public String getRazaoSocial() {
    return razaoSocial;
  }


  public void setRazaoSocial(String razaoSocial) {
    this.razaoSocial = razaoSocial;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ClientRequest clientRequest = (ClientRequest) o;
    return Objects.equals(this.cpfPcpj, clientRequest.cpfPcpj) &&
        Objects.equals(this.endereco, clientRequest.endereco) &&
        Objects.equals(this.nomeFantasia, clientRequest.nomeFantasia) &&
        Objects.equals(this.razaoSocial, clientRequest.razaoSocial);
  }

  @Override
  public int hashCode() {
    return Objects.hash(cpfPcpj, endereco, nomeFantasia, razaoSocial);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ClientRequest {\n");
    sb.append("    cpfPcpj: ").append(toIndentedString(cpfPcpj)).append("\n");
    sb.append("    endereco: ").append(toIndentedString(endereco)).append("\n");
    sb.append("    nomeFantasia: ").append(toIndentedString(nomeFantasia)).append("\n");
    sb.append("    razaoSocial: ").append(toIndentedString(razaoSocial)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

