/*
 * OS serive REST API
 * Documentação da API do OS service
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * ContatoRequest
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-09-26T16:38:53.309911-04:00[America/Havana]")
public class ContatoRequest {
  public static final String SERIALIZED_NAME_EMAIL = "email";
  @SerializedName(SERIALIZED_NAME_EMAIL)
  private String email;

  public static final String SERIALIZED_NAME_ID_CLIENTE = "idCliente";
  @SerializedName(SERIALIZED_NAME_ID_CLIENTE)
  private Integer idCliente;

  public static final String SERIALIZED_NAME_NOME = "nome";
  @SerializedName(SERIALIZED_NAME_NOME)
  private String nome;

  public static final String SERIALIZED_NAME_TELEFONE = "telefone";
  @SerializedName(SERIALIZED_NAME_TELEFONE)
  private String telefone;


  public ContatoRequest email(String email) {
    
    this.email = email;
    return this;
  }

   /**
   * email do contato
   * @return email
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "mail@mail.com", value = "email do contato")

  public String getEmail() {
    return email;
  }


  public void setEmail(String email) {
    this.email = email;
  }


  public ContatoRequest idCliente(Integer idCliente) {
    
    this.idCliente = idCliente;
    return this;
  }

   /**
   * codigo do cliente
   * @return idCliente
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "123", value = "codigo do cliente")

  public Integer getIdCliente() {
    return idCliente;
  }


  public void setIdCliente(Integer idCliente) {
    this.idCliente = idCliente;
  }


  public ContatoRequest nome(String nome) {
    
    this.nome = nome;
    return this;
  }

   /**
   * Nome do Contato
   * @return nome
  **/
  @ApiModelProperty(example = "Josenildo", required = true, value = "Nome do Contato")

  public String getNome() {
    return nome;
  }


  public void setNome(String nome) {
    this.nome = nome;
  }


  public ContatoRequest telefone(String telefone) {
    
    this.telefone = telefone;
    return this;
  }

   /**
   * Telefone do contato
   * @return telefone
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "1000-000", value = "Telefone do contato")

  public String getTelefone() {
    return telefone;
  }


  public void setTelefone(String telefone) {
    this.telefone = telefone;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ContatoRequest contatoRequest = (ContatoRequest) o;
    return Objects.equals(this.email, contatoRequest.email) &&
        Objects.equals(this.idCliente, contatoRequest.idCliente) &&
        Objects.equals(this.nome, contatoRequest.nome) &&
        Objects.equals(this.telefone, contatoRequest.telefone);
  }

  @Override
  public int hashCode() {
    return Objects.hash(email, idCliente, nome, telefone);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ContatoRequest {\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    idCliente: ").append(toIndentedString(idCliente)).append("\n");
    sb.append("    nome: ").append(toIndentedString(nome)).append("\n");
    sb.append("    telefone: ").append(toIndentedString(telefone)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

