/*
 * OS serive REST API
 * Documentação da API do OS service
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.BalancaRequest;
import org.openapitools.client.model.BalancaResponse;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for BalancaApi
 */
@Ignore
public class BalancaApiTest {

    private final BalancaApi api = new BalancaApi();

    
    /**
     * Altera uma balanca que ja exite
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void alterarResponseUsingPUTTest() throws ApiException {
        String token = null;
        BalancaRequest request = null;
        BalancaResponse response = api.alterarResponseUsingPUT(token, request);

        // TODO: test validations
    }
    
    /**
     * Consulta todas balancas
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void consultarBalancaUsingGETTest() throws ApiException {
        String token = null;
        List<BalancaResponse> response = api.consultarBalancaUsingGET(token);

        // TODO: test validations
    }
    
    /**
     * Cria uma nova balanca
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void inserirnovaBalancaUsingPOSTTest() throws ApiException {
        String token = null;
        BalancaRequest request = null;
        BalancaResponse response = api.inserirnovaBalancaUsingPOST(token, request);

        // TODO: test validations
    }
    
    /**
     * removerBalanca
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void removerBalancaUsingDELETETest() throws ApiException {
        String balancaId = null;
        String token = null;
        String response = api.removerBalancaUsingDELETE(balancaId, token);

        // TODO: test validations
    }
    
}
