/*
 * OS serive REST API
 * Documentação da API do OS service
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.EquipamentoRequest;
import org.openapitools.client.model.EquipamentoResponse;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for EquipamentoApi
 */
@Ignore
public class EquipamentoApiTest {

    private final EquipamentoApi api = new EquipamentoApi();

    
    /**
     * Altera um equipamento que ja exite
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void alterarEquipamentoUsingPUTTest() throws ApiException {
        String token = null;
        EquipamentoRequest equipamentoRequest = null;
        EquipamentoResponse response = api.alterarEquipamentoUsingPUT(token, equipamentoRequest);

        // TODO: test validations
    }
    
    /**
     * Consulta todas balancas
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void consultarEquipamentoUsingGETTest() throws ApiException {
        String token = null;
        List<EquipamentoResponse> response = api.consultarEquipamentoUsingGET(token);

        // TODO: test validations
    }
    
    /**
     * Cadastrar um equipamento
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void inserirEquipamentoUsingPOSTTest() throws ApiException {
        String token = null;
        EquipamentoRequest equipamentoRequest = null;
        EquipamentoResponse response = api.inserirEquipamentoUsingPOST(token, equipamentoRequest);

        // TODO: test validations
    }
    
    /**
     * deleta um equipamento que ja exite
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void removerEquipamentoUsingDELETETest() throws ApiException {
        Integer equipamentoId = null;
        String token = null;
        String response = api.removerEquipamentoUsingDELETE(equipamentoId, token);

        // TODO: test validations
    }
    
}
