/*
 * OS serive REST API
 * Documentação da API do OS service
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for BalancaRequest
 */
public class BalancaRequestTest {
    private final BalancaRequest model = new BalancaRequest();

    /**
     * Model tests for BalancaRequest
     */
    @Test
    public void testBalancaRequest() {
        // TODO: test BalancaRequest
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'marca'
     */
    @Test
    public void marcaTest() {
        // TODO: test marca
    }

    /**
     * Test the property 'modelo'
     */
    @Test
    public void modeloTest() {
        // TODO: test modelo
    }

    /**
     * Test the property 'nome'
     */
    @Test
    public void nomeTest() {
        // TODO: test nome
    }

    /**
     * Test the property 'numeroImetro'
     */
    @Test
    public void numeroImetroTest() {
        // TODO: test numeroImetro
    }

    /**
     * Test the property 'portaria'
     */
    @Test
    public void portariaTest() {
        // TODO: test portaria
    }

}
