/*
 * OS serive REST API
 * Documentação da API do OS service
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for ClientRequest
 */
public class ClientRequestTest {
    private final ClientRequest model = new ClientRequest();

    /**
     * Model tests for ClientRequest
     */
    @Test
    public void testClientRequest() {
        // TODO: test ClientRequest
    }

    /**
     * Test the property 'cpfPcpj'
     */
    @Test
    public void cpfPcpjTest() {
        // TODO: test cpfPcpj
    }

    /**
     * Test the property 'endereco'
     */
    @Test
    public void enderecoTest() {
        // TODO: test endereco
    }

    /**
     * Test the property 'nomeFantasia'
     */
    @Test
    public void nomeFantasiaTest() {
        // TODO: test nomeFantasia
    }

    /**
     * Test the property 'razaoSocial'
     */
    @Test
    public void razaoSocialTest() {
        // TODO: test razaoSocial
    }

}
