/*
 * OS serive REST API
 * Documentação da API do OS service
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for ContatoResponse
 */
public class ContatoResponseTest {
    private final ContatoResponse model = new ContatoResponse();

    /**
     * Model tests for ContatoResponse
     */
    @Test
    public void testContatoResponse() {
        // TODO: test ContatoResponse
    }

    /**
     * Test the property 'email'
     */
    @Test
    public void emailTest() {
        // TODO: test email
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'nome'
     */
    @Test
    public void nomeTest() {
        // TODO: test nome
    }

    /**
     * Test the property 'telefone'
     */
    @Test
    public void telefoneTest() {
        // TODO: test telefone
    }

}
