/*
 * OS serive REST API
 * Documentação da API do OS service
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiCallback;
import org.openapitools.client.ApiClient;
import org.openapitools.client.ApiException;
import org.openapitools.client.ApiResponse;
import org.openapitools.client.Configuration;
import org.openapitools.client.Pair;
import org.openapitools.client.ProgressRequestBody;
import org.openapitools.client.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import org.openapitools.client.model.EquipamentoRequest;
import org.openapitools.client.model.EquipamentoResponse;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class EquipamentoApi {
    private ApiClient localVarApiClient;

    public EquipamentoApi() {
        this(Configuration.getDefaultApiClient());
    }

    public EquipamentoApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    /**
     * Build call for alterarEquipamentoUsingPUT
     * @param token token (required)
     * @param equipamentoRequest equipamentoRequest (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Retorna info do equipamento </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Erro de autenticacao </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Erro não mapeado </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call alterarEquipamentoUsingPUTCall(String token, EquipamentoRequest equipamentoRequest, final ApiCallback _callback) throws ApiException {
        Object localVarPostBody = equipamentoRequest;

        // create path and map variables
        String localVarPath = "/equipamento/alterar";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (token != null) {
            localVarHeaderParams.put("token", localVarApiClient.parameterToString(token));
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(localVarPath, "PUT", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call alterarEquipamentoUsingPUTValidateBeforeCall(String token, EquipamentoRequest equipamentoRequest, final ApiCallback _callback) throws ApiException {
        
        // verify the required parameter 'token' is set
        if (token == null) {
            throw new ApiException("Missing the required parameter 'token' when calling alterarEquipamentoUsingPUT(Async)");
        }
        
        // verify the required parameter 'equipamentoRequest' is set
        if (equipamentoRequest == null) {
            throw new ApiException("Missing the required parameter 'equipamentoRequest' when calling alterarEquipamentoUsingPUT(Async)");
        }
        

        okhttp3.Call localVarCall = alterarEquipamentoUsingPUTCall(token, equipamentoRequest, _callback);
        return localVarCall;

    }

    /**
     * Altera um equipamento que ja exite
     * 
     * @param token token (required)
     * @param equipamentoRequest equipamentoRequest (required)
     * @return EquipamentoResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Retorna info do equipamento </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Erro de autenticacao </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Erro não mapeado </td><td>  -  </td></tr>
     </table>
     */
    public EquipamentoResponse alterarEquipamentoUsingPUT(String token, EquipamentoRequest equipamentoRequest) throws ApiException {
        ApiResponse<EquipamentoResponse> localVarResp = alterarEquipamentoUsingPUTWithHttpInfo(token, equipamentoRequest);
        return localVarResp.getData();
    }

    /**
     * Altera um equipamento que ja exite
     * 
     * @param token token (required)
     * @param equipamentoRequest equipamentoRequest (required)
     * @return ApiResponse&lt;EquipamentoResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Retorna info do equipamento </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Erro de autenticacao </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Erro não mapeado </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<EquipamentoResponse> alterarEquipamentoUsingPUTWithHttpInfo(String token, EquipamentoRequest equipamentoRequest) throws ApiException {
        okhttp3.Call localVarCall = alterarEquipamentoUsingPUTValidateBeforeCall(token, equipamentoRequest, null);
        Type localVarReturnType = new TypeToken<EquipamentoResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Altera um equipamento que ja exite (asynchronously)
     * 
     * @param token token (required)
     * @param equipamentoRequest equipamentoRequest (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Retorna info do equipamento </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Erro de autenticacao </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Erro não mapeado </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call alterarEquipamentoUsingPUTAsync(String token, EquipamentoRequest equipamentoRequest, final ApiCallback<EquipamentoResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = alterarEquipamentoUsingPUTValidateBeforeCall(token, equipamentoRequest, _callback);
        Type localVarReturnType = new TypeToken<EquipamentoResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for consultarEquipamentoUsingGET
     * @param token Token de acesso (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Retorna lista de balanca </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Erro de autenticacao </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Erro não mapeado </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call consultarEquipamentoUsingGETCall(String token, final ApiCallback _callback) throws ApiException {
        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/equipamento/consultar";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (token != null) {
            localVarHeaderParams.put("token", localVarApiClient.parameterToString(token));
        }

        final String[] localVarAccepts = {
            "*/*"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call consultarEquipamentoUsingGETValidateBeforeCall(String token, final ApiCallback _callback) throws ApiException {
        
        // verify the required parameter 'token' is set
        if (token == null) {
            throw new ApiException("Missing the required parameter 'token' when calling consultarEquipamentoUsingGET(Async)");
        }
        

        okhttp3.Call localVarCall = consultarEquipamentoUsingGETCall(token, _callback);
        return localVarCall;

    }

    /**
     * Consulta todas balancas
     * 
     * @param token Token de acesso (required)
     * @return List&lt;EquipamentoResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Retorna lista de balanca </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Erro de autenticacao </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Erro não mapeado </td><td>  -  </td></tr>
     </table>
     */
    public List<EquipamentoResponse> consultarEquipamentoUsingGET(String token) throws ApiException {
        ApiResponse<List<EquipamentoResponse>> localVarResp = consultarEquipamentoUsingGETWithHttpInfo(token);
        return localVarResp.getData();
    }

    /**
     * Consulta todas balancas
     * 
     * @param token Token de acesso (required)
     * @return ApiResponse&lt;List&lt;EquipamentoResponse&gt;&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Retorna lista de balanca </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Erro de autenticacao </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Erro não mapeado </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<List<EquipamentoResponse>> consultarEquipamentoUsingGETWithHttpInfo(String token) throws ApiException {
        okhttp3.Call localVarCall = consultarEquipamentoUsingGETValidateBeforeCall(token, null);
        Type localVarReturnType = new TypeToken<List<EquipamentoResponse>>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Consulta todas balancas (asynchronously)
     * 
     * @param token Token de acesso (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Retorna lista de balanca </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Erro de autenticacao </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Erro não mapeado </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call consultarEquipamentoUsingGETAsync(String token, final ApiCallback<List<EquipamentoResponse>> _callback) throws ApiException {

        okhttp3.Call localVarCall = consultarEquipamentoUsingGETValidateBeforeCall(token, _callback);
        Type localVarReturnType = new TypeToken<List<EquipamentoResponse>>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for inserirEquipamentoUsingPOST
     * @param token token (required)
     * @param equipamentoRequest equipamentoRequest (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Retorna info dos equipamento </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Erro de autenticacao </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Erro não mapeado </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call inserirEquipamentoUsingPOSTCall(String token, EquipamentoRequest equipamentoRequest, final ApiCallback _callback) throws ApiException {
        Object localVarPostBody = equipamentoRequest;

        // create path and map variables
        String localVarPath = "/equipamento/cadastrar";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (token != null) {
            localVarHeaderParams.put("token", localVarApiClient.parameterToString(token));
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call inserirEquipamentoUsingPOSTValidateBeforeCall(String token, EquipamentoRequest equipamentoRequest, final ApiCallback _callback) throws ApiException {
        
        // verify the required parameter 'token' is set
        if (token == null) {
            throw new ApiException("Missing the required parameter 'token' when calling inserirEquipamentoUsingPOST(Async)");
        }
        
        // verify the required parameter 'equipamentoRequest' is set
        if (equipamentoRequest == null) {
            throw new ApiException("Missing the required parameter 'equipamentoRequest' when calling inserirEquipamentoUsingPOST(Async)");
        }
        

        okhttp3.Call localVarCall = inserirEquipamentoUsingPOSTCall(token, equipamentoRequest, _callback);
        return localVarCall;

    }

    /**
     * Cadastrar um equipamento
     * 
     * @param token token (required)
     * @param equipamentoRequest equipamentoRequest (required)
     * @return EquipamentoResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Retorna info dos equipamento </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Erro de autenticacao </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Erro não mapeado </td><td>  -  </td></tr>
     </table>
     */
    public EquipamentoResponse inserirEquipamentoUsingPOST(String token, EquipamentoRequest equipamentoRequest) throws ApiException {
        ApiResponse<EquipamentoResponse> localVarResp = inserirEquipamentoUsingPOSTWithHttpInfo(token, equipamentoRequest);
        return localVarResp.getData();
    }

    /**
     * Cadastrar um equipamento
     * 
     * @param token token (required)
     * @param equipamentoRequest equipamentoRequest (required)
     * @return ApiResponse&lt;EquipamentoResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Retorna info dos equipamento </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Erro de autenticacao </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Erro não mapeado </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<EquipamentoResponse> inserirEquipamentoUsingPOSTWithHttpInfo(String token, EquipamentoRequest equipamentoRequest) throws ApiException {
        okhttp3.Call localVarCall = inserirEquipamentoUsingPOSTValidateBeforeCall(token, equipamentoRequest, null);
        Type localVarReturnType = new TypeToken<EquipamentoResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Cadastrar um equipamento (asynchronously)
     * 
     * @param token token (required)
     * @param equipamentoRequest equipamentoRequest (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Retorna info dos equipamento </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Erro de autenticacao </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Erro não mapeado </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call inserirEquipamentoUsingPOSTAsync(String token, EquipamentoRequest equipamentoRequest, final ApiCallback<EquipamentoResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = inserirEquipamentoUsingPOSTValidateBeforeCall(token, equipamentoRequest, _callback);
        Type localVarReturnType = new TypeToken<EquipamentoResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for removerEquipamentoUsingDELETE
     * @param equipamentoId equipamentoId (required)
     * @param token token (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Retorna \&quot;OK\&quot;  </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Erro de autenticacao </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Erro não mapeado </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call removerEquipamentoUsingDELETECall(Integer equipamentoId, String token, final ApiCallback _callback) throws ApiException {
        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/equipamento/remover";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (equipamentoId != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("equipamentoId", equipamentoId));
        }

        if (token != null) {
            localVarHeaderParams.put("token", localVarApiClient.parameterToString(token));
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(localVarPath, "DELETE", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call removerEquipamentoUsingDELETEValidateBeforeCall(Integer equipamentoId, String token, final ApiCallback _callback) throws ApiException {
        
        // verify the required parameter 'equipamentoId' is set
        if (equipamentoId == null) {
            throw new ApiException("Missing the required parameter 'equipamentoId' when calling removerEquipamentoUsingDELETE(Async)");
        }
        
        // verify the required parameter 'token' is set
        if (token == null) {
            throw new ApiException("Missing the required parameter 'token' when calling removerEquipamentoUsingDELETE(Async)");
        }
        

        okhttp3.Call localVarCall = removerEquipamentoUsingDELETECall(equipamentoId, token, _callback);
        return localVarCall;

    }

    /**
     * deleta um equipamento que ja exite
     * 
     * @param equipamentoId equipamentoId (required)
     * @param token token (required)
     * @return String
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Retorna \&quot;OK\&quot;  </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Erro de autenticacao </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Erro não mapeado </td><td>  -  </td></tr>
     </table>
     */
    public String removerEquipamentoUsingDELETE(Integer equipamentoId, String token) throws ApiException {
        ApiResponse<String> localVarResp = removerEquipamentoUsingDELETEWithHttpInfo(equipamentoId, token);
        return localVarResp.getData();
    }

    /**
     * deleta um equipamento que ja exite
     * 
     * @param equipamentoId equipamentoId (required)
     * @param token token (required)
     * @return ApiResponse&lt;String&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Retorna \&quot;OK\&quot;  </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Erro de autenticacao </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Erro não mapeado </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<String> removerEquipamentoUsingDELETEWithHttpInfo(Integer equipamentoId, String token) throws ApiException {
        okhttp3.Call localVarCall = removerEquipamentoUsingDELETEValidateBeforeCall(equipamentoId, token, null);
        Type localVarReturnType = new TypeToken<String>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * deleta um equipamento que ja exite (asynchronously)
     * 
     * @param equipamentoId equipamentoId (required)
     * @param token token (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Retorna \&quot;OK\&quot;  </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Erro de autenticacao </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Erro não mapeado </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call removerEquipamentoUsingDELETEAsync(Integer equipamentoId, String token, final ApiCallback<String> _callback) throws ApiException {

        okhttp3.Call localVarCall = removerEquipamentoUsingDELETEValidateBeforeCall(equipamentoId, token, _callback);
        Type localVarReturnType = new TypeToken<String>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
}
